// source: update_sync.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

import jspb, { Message, BinaryReader, BinaryWriter } from 'google-protobuf';
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.UpdateProto', null, global);
goog.exportSymbol('proto.UpdateSyncProto', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UpdateProto = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.UpdateProto, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.UpdateProto.displayName = 'proto.UpdateProto';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UpdateSyncProto = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, proto.UpdateSyncProto.repeatedFields_, null);
};
goog.inherits(proto.UpdateSyncProto, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.UpdateSyncProto.displayName = 'proto.UpdateSyncProto';
}



if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UpdateProto.prototype.toObject = function(opt_includeInstance) {
  return proto.UpdateProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UpdateProto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UpdateProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: Message.getFieldWithDefault(msg, 1, 0),
    x: Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    z: Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    rotation: Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UpdateProto}
 */
proto.UpdateProto.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.UpdateProto;
  return proto.UpdateProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UpdateProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UpdateProto}
 */
proto.UpdateProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setZ(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRotation(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UpdateProto.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.UpdateProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UpdateProto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UpdateProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getZ();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getRotation();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional uint32 id = 1;
 * @return {number}
 */
proto.UpdateProto.prototype.getId = function() {
  return /** @type {number} */ (Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.UpdateProto} returns this
 */
proto.UpdateProto.prototype.setId = function(value) {
  return Message.setProto3IntField(this, 1, value);
};


/**
 * optional float x = 2;
 * @return {number}
 */
proto.UpdateProto.prototype.getX = function() {
  return /** @type {number} */ (Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.UpdateProto} returns this
 */
proto.UpdateProto.prototype.setX = function(value) {
  return Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float z = 3;
 * @return {number}
 */
proto.UpdateProto.prototype.getZ = function() {
  return /** @type {number} */ (Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.UpdateProto} returns this
 */
proto.UpdateProto.prototype.setZ = function(value) {
  return Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float rotation = 4;
 * @return {number}
 */
proto.UpdateProto.prototype.getRotation = function() {
  return /** @type {number} */ (Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.UpdateProto} returns this
 */
proto.UpdateProto.prototype.setRotation = function(value) {
  return Message.setProto3FloatField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.UpdateSyncProto.repeatedFields_ = [1];



if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UpdateSyncProto.prototype.toObject = function(opt_includeInstance) {
  return proto.UpdateSyncProto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UpdateSyncProto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UpdateSyncProto.toObject = function(includeInstance, msg) {
  var f, obj = {
    ducksList: Message.toObjectList(msg.getDucksList(),
    proto.UpdateProto.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UpdateSyncProto}
 */
proto.UpdateSyncProto.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.UpdateSyncProto;
  return proto.UpdateSyncProto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UpdateSyncProto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UpdateSyncProto}
 */
proto.UpdateSyncProto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.UpdateProto;
      reader.readMessage(value,proto.UpdateProto.deserializeBinaryFromReader);
      msg.addDucks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UpdateSyncProto.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.UpdateSyncProto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UpdateSyncProto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UpdateSyncProto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDucksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.UpdateProto.serializeBinaryToWriter
    );
  }
};


/**
 * repeated UpdateProto ducks = 1;
 * @return {!Array<!proto.UpdateProto>}
 */
proto.UpdateSyncProto.prototype.getDucksList = function() {
  return /** @type{!Array<!proto.UpdateProto>} */ (
    Message.getRepeatedWrapperField(this, proto.UpdateProto, 1));
};


/**
 * @param {!Array<!proto.UpdateProto>} value
 * @return {!proto.UpdateSyncProto} returns this
*/
proto.UpdateSyncProto.prototype.setDucksList = function(value) {
  return Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.UpdateProto=} opt_value
 * @param {number=} opt_index
 * @return {!proto.UpdateProto}
 */
proto.UpdateSyncProto.prototype.addDucks = function(opt_value, opt_index) {
  return Message.addToRepeatedWrapperField(this, 1, opt_value, proto.UpdateProto, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.UpdateSyncProto} returns this
 */
proto.UpdateSyncProto.prototype.clearDucksList = function() {
  return this.setDucksList([]);
};


// goog.object.extend(exports, proto);
export default proto;
